### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81

### ISSUE THREAD

**Issue by seajhawk** [MeltanoLabs/tap-csv#44]
While testing Meltano I ran into this issue:

`[info     ] UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5719: character maps to <undefined>`

1. Why is this surfacing as `[info]` instead of error?

2. I wondered if this might happen because in the Pandas based extractor/loader I wrote before trying Meltano I had to play with encodings because of non-UTF8 chars.

I think a reasonable fix would be to add a config setting of `encoding:` for tap-csv, and then if set use the specified encoding it in the call to open() in the get_rows() function in client.py. e.g:
`with open(file_path, "r", encoding=encoding) as f:`

**Comment by pnadolny13** [comment]
>Why is this surfacing as [info] instead of error?

@seajhawk Interesting, I'm not sure. Its hard to tell if its something the tap is doing or if Meltano is re-raising the log incorrectly.

>I think a reasonable fix would be to add a config setting of encoding: for tap-csv, and then if set use the specified encoding it in the call to open() in the get_rows() function in client.py. e.g:
with open(file_path, "r", encoding=encoding) as f:

I agree, that sounds like a reasonable addition to the tap! Is this something you'd consider contributing a PR for?

**Comment by charris-msft** [comment]
@pnadolny13 - took me a while to find the time, but I did just submit a PR. https://github.com/MeltanoLabs/tap-csv/pull/58

**Comment by pnadolny13** [comment]
Closing because https://github.com/MeltanoLabs/tap-csv/pull/58 merged. Thanks again @charris-msft

**Comment by seajhawk** [comment]
@pnadolny13 - What is the process for getting everything updated so I get the latest version of this tap on my local machine?

it seems like I should be able to run `meltano upgrade`, but that didn't pull the latest and when I look at [Meltano Hub](https://hub.meltano.com/extractors/tap-csv), it says the last update was '05 Mar 2022'.

**Comment by pnadolny13** [comment]
@seajhawk the upgrade command doesnt upgrade plugin versions https://docs.meltano.com/reference/command-line-interface#upgrade.

If you dont have the tap version pinned then re-installing using `--clean` https://docs.meltano.com/reference/command-line-interface#install should do the trick.

If you've got the [tap version pinned](https://docs.meltano.com/guide/plugin-management#pinning-a-plugin-to-a-specific-version) then bump it to v0.0.6 and run the `--clean` install.
