### ISSUE TITLE
Hard to find errors

### ISSUE THREAD

**Issue by seajhawk** [MeltanoLabs/tap-csv#53]
(This is a partial dup of another issue, but I'll let that one focus on file encoding)

I'm getting an error when trying to `meltao run` - can you find it?

![image](https://user-images.githubusercontent.com/18316676/184448439-def8e460-87f9-4f94-96d0-60c43c5a03c7.png)

How about now?
![image](https://user-images.githubusercontent.com/18316676/184448752-92503de3-eefa-4ae8-b60a-431de404f771.png)

If the green `info` text accurately matched the level=WARNING or level=CRITICAL it would be infinitely easier to figure out what's going on.

**Comment by pnadolny13** [comment]
@seajhawk I agree that there are improvements that should be made here but I think this issue is better suited for https://github.com/meltano/meltano since its related to how meltano re-logs the tap/target logs. Does that make sense?

**Comment by pnadolny13** [comment]
Closing this issue because its related to meltano vs the tap itself. Feel free to re-open if thats not true!
